Vagrant.configure(2) do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "bcarolleS" do |control|
    control.vm.hostname = "bcarolleS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.name = "bcarolleS"
      v.memory = 1024
      v.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      sudo apt update && sudo apt upgrade -y
      sudo apt install net-tools -y curl
      sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -
      sudo kubectl apply -f /vagrant/deployments.yaml
      sudo kubectl apply -f /vagrant/services.yaml
      sudo kubectl apply -f /vagrant/ingress.yaml
    SHELL
  end
end