Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/jammy64"
  # config.vm.box_url = REDACTED

  config.vm.define "bcarolleS" do |control|
    control.vm.hostname = "bcarolleS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.name = "bcarolleS"
      v.memory = 1024
      v.cpus = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt update && sudo apt upgrade -y
      sudo apt install net-tools -y
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end

  config.vm.define "bcarolleSW" do |control|
    control.vm.hostname = "bcarolleSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.name = "bcarolleSW"
      v.memory = 1024
      v.cpus = 1
    end
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt update && sudo apt upgrade -y
      sudo apt install net-tools -y
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end
end