Vagrant.configure(2) do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "bcarolleS" do |control|
    control.vm.hostname = "bcarolleS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.name = "bcarolleS"
      v.memory = 2048
      v.cpus = 4
    end
    control.vm.provision "shell", inline: <<-SHELL
      chmod +x /vagrant/install.sh
      sudo /vagrant/install.sh
    SHELL
  end
end